apiVersion: v1
kind: Pod
metadata:
  name: memkill
  namespace: default
spec:
  containers:
  - image: test/memoryeater
    command:
      - sleep
      - "100"
    imagePullPolicy: IfNotPresent
    name: memkill
  restartPolicy: Always
