apiVersion: v1
kind: Pod
metadata:
  name: dockstress
  namespace: default
spec:
  containers:
  - image: prasenforu/dockstress
    command:
      - sleep
      - "100"
    imagePullPolicy: IfNotPresent
    name: dockstress
  restartPolicy: Always
